#!/usr/bin/env node
/**
 * scripts/db-migrate.js — direct-exec migration runner.
 *
 * Replaces the drizzle-orm/better-sqlite3 migrator (which requires
 * `meta/_journal.json` generated by drizzle-kit) with a hand-rolled runner.
 *
 * Why direct-exec and not drizzle's migrator:
 *   - The 0000_initial.sql is hand-written (not drizzle-kit-generated), so
 *     `meta/_journal.json` and `meta/0000_snapshot.json` don't exist.
 *   - We tried adopting drizzle-kit generate; the round-trip introduced enough
 *     drift on our hand-tuned CHECK constraints + foreign-key behaviors that
 *     direct-exec is simpler. Tracked as DRIFT-test3-015.
 *   - This script is idempotent: it tracks applied migrations in a
 *     `__migrations` table identical in shape to drizzle's `__drizzle_migrations`,
 *     so a future swap back to drizzle's migrator is mechanical (just rename).
 *
 * Usage:
 *   pnpm db:migrate          (applies all pending)
 *   pnpm db:migrate --status (lists applied + pending, no writes)
 *
 * Statement-breakpoint discipline: SQL files use `--> statement-breakpoint` as
 * a separator (drizzle convention). We split on it so DDL with embedded
 * semicolons (in CHECK constraints) doesn't break.
 */

'use strict';

const fs = require('node:fs');
const path = require('node:path');
const Database = require('better-sqlite3');

const MIGRATIONS_DIR = path.resolve(__dirname, '..', 'drizzle', 'migrations');
const DB_PATH = process.env.DB_PATH || './data/tutorials.db';

function listMigrationFiles() {
  if (!fs.existsSync(MIGRATIONS_DIR)) {
    throw new Error(`migrations dir not found: ${MIGRATIONS_DIR}`);
  }
  return fs
    .readdirSync(MIGRATIONS_DIR)
    .filter((f) => f.endsWith('.sql'))
    .sort();
}

function ensureMigrationsTable(db) {
  db.exec(`
    CREATE TABLE IF NOT EXISTS __migrations (
      id integer PRIMARY KEY AUTOINCREMENT,
      tag text NOT NULL UNIQUE,
      applied_at integer NOT NULL
    )
  `);
}

function loadAppliedTags(db) {
  const rows = db.prepare('SELECT tag FROM __migrations ORDER BY id').all();
  return new Set(rows.map((r) => r.tag));
}

function applyMigration(db, file) {
  const tag = file.replace(/\.sql$/, '');
  const sql = fs.readFileSync(path.join(MIGRATIONS_DIR, file), 'utf8');
  // Strip the drizzle statement-breakpoint markers and split if present.
  // SQLite's db.exec runs multi-statement SQL fine, but the breakpoints help
  // when a single statement contains semicolons inside parens.
  const statements = sql
    .split('--> statement-breakpoint')
    .map((s) => s.trim())
    .filter((s) => s.length > 0);

  const txn = db.transaction(() => {
    for (const stmt of statements) {
      db.exec(stmt);
    }
    db.prepare('INSERT INTO __migrations (tag, applied_at) VALUES (?, ?)').run(
      tag,
      Math.floor(Date.now() / 1000),
    );
  });
  txn();
}

function main() {
  const args = process.argv.slice(2);
  const isStatus = args.includes('--status');

  if (!fs.existsSync(path.dirname(DB_PATH))) {
    fs.mkdirSync(path.dirname(DB_PATH), { recursive: true });
  }
  const db = new Database(DB_PATH);
  db.pragma('foreign_keys = ON');

  ensureMigrationsTable(db);
  const applied = loadAppliedTags(db);
  const files = listMigrationFiles();
  const pending = files.filter((f) => !applied.has(f.replace(/\.sql$/, '')));

  if (isStatus) {
    console.log(`db: ${DB_PATH}`);
    console.log(`applied: ${[...applied].sort().join(', ') || '(none)'}`);
    console.log(`pending: ${pending.join(', ') || '(none)'}`);
    db.close();
    return;
  }

  if (pending.length === 0) {
    console.log('[migrate] no pending migrations');
    db.close();
    return;
  }

  for (const file of pending) {
    process.stdout.write(`[migrate] applying ${file} ... `);
    try {
      applyMigration(db, file);
      console.log('OK');
    } catch (err) {
      console.log('FAILED');
      console.error(err);
      db.close();
      process.exit(1);
    }
  }
  db.close();
}

main();
